name: Deploy to Okteto

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - uses: okteto/login@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        
    - name: "Activate personal namespace"
      uses: okteto/namespace@latest
      with:
        name: isandesh1986
    
    - name: "Build Java Image"
      uses: okteto/build@latest
      with:
        tag: registry.cloud.okteto.net/isandesh1986/mts-java:latest
        
    - name: "Build Angular Image"
      uses: okteto/build@latest
      with:
        tag: registry.cloud.okteto.net/isandesh1986/mts-angular:latest       

    - name: "Create deployment"
      uses: okteto/apply@latest
      with:
        manifest: deployment.yaml
