name: Deploy to Okteto

on: pull_request

jobs:

  preview:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        
    - name: "Activate personal namespace"
      uses: okteto/namespace@master
      with:
        name: isandesh1986

    - name: "Create deployment"
      uses: okteto/apply@master
      with:
        manifest: deployment.yaml
