name: Deploy to Okteto

on: pull_request

jobs:

  preview:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        
    - name: "Activate personal namespace"
      uses: okteto/namespace@master
      with:
        name: isandesh1986
    
    - name: "Build Java Image"
      uses: okteto/build@master
      with:
        tag: registry.cloud.okteto.net/isandesh1986/mts-java
        file: java/Dockerfile.githubactions

    - name: "Build Angular Image"
      uses: okteto/build@master
      with:
        tag: registry.cloud.okteto.net/isandesh1986/mts-angular
        file: angular/Dockerfile.githubactions

    - name: "Create deployment"
      uses: okteto/apply@master
      with:
        manifest: deployment.yaml
